// <auto-generated />
namespace Vidly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RenamecolumnAvailabilitytoNumberAvailableandadddatatothiscolumn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RenamecolumnAvailabilitytoNumberAvailableandadddatatothiscolumn));
        
        string IMigrationMetadata.Id
        {
            get { return "202305111504336_Rename column Availability to NumberAvailable and add data to this column"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
